# Generated by Django 3.1 on 2020-08-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survived', models.BooleanField(default=True, verbose_name='Survived')),
                ('pclass', models.PositiveSmallIntegerField(verbose_name='Passenger class')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('sex', models.CharField(max_length=64, verbose_name='Sex')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('sib_sp', models.PositiveSmallIntegerField(verbose_name='SibSp')),
                ('parch', models.CharField(max_length=128, verbose_name='Parch')),
                ('ticket', models.CharField(max_length=128, verbose_name='Ticket')),
                ('fare', models.CharField(max_length=128, verbose_name='Fare')),
                ('cabin', models.CharField(max_length=128, verbose_name='Cabin')),
                ('embarked', models.CharField(max_length=128, verbose_name='Embarked')),
            ],
        ),
    ]
