# Generated by Django 3.1 on 2020-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='pclass',
            field=models.IntegerField(verbose_name='Passenger class'),
        ),
    ]
