# Generated by Django 3.1 on 2020-08-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_passenger_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
            preserve_default=False,
        ),
    ]
